name: Notify Backend on Push

on:
  push:
    paths:
      - 'server/**'

jobs:
  slack_notifier:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification on Slack using Webhooks
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": ":gear: *Push to backend* by ${{ github.actor }} on branch `${{ github.ref_name }}`.\n<${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|View Commit>"
            }
        env:
          SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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